12-Feb-2020 19:18:07 - DEBUG - pywebcopy.configs.(unknown function):0 - {'debug': False, 'log_file': 'C:\\Users\\guoyu\\OneDrive\\Desktop\\course\\180 DB\\combine\\path\\to\\downloads\\some-fancy-name\\pywebcopy_log.log', 'project_name': 'some-fancy-name', 'project_folder': 'C:\\Users\\guoyu\\OneDrive\\Desktop\\course\\180 DB\\combine\\path\\to\\downloads\\some-fancy-name', 'over_write': False, 'bypass_robots': False, 'zip_project_folder': True, 'delete_project_folder': False, 'allowed_file_ext': ['.html', '.php', '.asp', '.aspx', '.htm', '.xhtml', '.css', '.json', '.js', '.xml', '.svg', '.gif', '.ico', '.jpeg', '.pdf', '.jpg', '.png', '.ttf', '.eot', '.otf', '.woff', '.woff2', '.pwcf'], 'http_headers': {'Accept-Language': 'en-US,en;q=0.9', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 PyWebCopyBot/6.1.1'}, 'load_css': True, 'load_javascript': True, 'load_images': True, 'join_timeout': None, 'project_url': 'https://github.com/CaoZ/JD-Coin/issues/33'}
12-Feb-2020 19:18:07 - DEBUG - urllib3.connectionpool.(unknown function):0 - Starting new HTTPS connection (1): github.com:443
12-Feb-2020 19:18:08 - DEBUG - urllib3.connectionpool.(unknown function):0 - https://github.com:443 "GET /robots.txt HTTP/1.1" 200 None
12-Feb-2020 19:18:08 - INFO - pywebcopy.configs.(unknown function):0 - Got response 200 from https://github.com/robots.txt
12-Feb-2020 19:18:08 - ERROR - pywebcopy.configs.(unknown function):0 - Website doesn't allow access to the url https://github.com/CaoZ/JD-Coin/issues/33
